var month = ['January', 'February', 'March'];
console.log(month[0]);
console.log(month[2]);
month[3] = 'April';
console.log(month.toString());
month[6] = 'July';
console.log(month.toString());
var theMonthOff = month.slice(6);
console.log(theMonthOff.toString());
console.log(month.toString());
month.splice(4,2, "May", "June");
console.log(month.toString());
month.push('August');
console.log(month.toString());
let extras = month.pop();
console.log(month.toString());
console.log(extras);
month.sort();
console.log(month.toString());